### ISSUE TITLE
Virus in latest TMCP?

### ISSUE THREAD

**Issue by darvids0n** [donadigo/donadigo.github.io#8]
Windows Defender is detecting Wacatac in patch 1.4.9. Is there some reason the patch needs to use the same hooks as a trojan?

**Comment by donadigo** [comment]
Nothing major changed in how the patch works in 1.4.9. It's Windows Defender that detects there's a new file out there and still treats it as a virus.

**Comment by darvids0n** [comment]
OK, cheers. I've reported it as a false positive here: https://www.microsoft.com/en-us/wdsi/filesubmission
